// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_AcessoADatos.Models;

namespace Proyecto_AcessoADatos.Migrations
{
    [DbContext(typeof(PlaceMyBetContext))]
    [Migration("20191213181738_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Proyecto_AcessoADatos.Models.apuestas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cuota");

                    b.Property<float>("Dinero_apostado");

                    b.Property<int>("ID_MERCADO");

                    b.Property<int>("ID_USUARIOS");

                    b.Property<string>("Tipo_apuesta");

                    b.Property<int?>("mercadoid");

                    b.HasKey("Id");

                    b.HasIndex("mercadoid");

                    b.ToTable("Apuestas");
                });

            modelBuilder.Entity("Proyecto_AcessoADatos.Models.cuenta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre_banco");

                    b.Property<string>("Num_tarjeta_vinculada");

                    b.Property<decimal>("Saldo_actual");

                    b.Property<int>("UsuarioId");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("Proyecto_AcessoADatos.Models.evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Equipo_Local");

                    b.Property<string>("Equipo_visitante");

                    b.HasKey("EventoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Proyecto_AcessoADatos.Models.mercado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cuota_over");

                    b.Property<decimal>("Cuota_under");

                    b.Property<float>("Dinero_over");

                    b.Property<float>("Dinero_under");

                    b.Property<int?>("EventoId");

                    b.Property<int>("IDEvento");

                    b.Property<string>("tipo_mercado");

                    b.HasKey("id");

                    b.HasIndex("EventoId");

                    b.ToTable("Mercados");
                });

            modelBuilder.Entity("Proyecto_AcessoADatos.Models.usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<int>("Edad");

                    b.Property<string>("Email");

                    b.Property<string>("Nombre");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_AcessoADatos.Models.apuestas", b =>
                {
                    b.HasOne("Proyecto_AcessoADatos.Models.mercado", "mercado")
                        .WithMany("Apuestas")
                        .HasForeignKey("mercadoid");
                });

            modelBuilder.Entity("Proyecto_AcessoADatos.Models.cuenta", b =>
                {
                    b.HasOne("Proyecto_AcessoADatos.Models.usuario", "Usuario")
                        .WithOne("cuenta")
                        .HasForeignKey("Proyecto_AcessoADatos.Models.cuenta", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Proyecto_AcessoADatos.Models.mercado", b =>
                {
                    b.HasOne("Proyecto_AcessoADatos.Models.evento", "evento")
                        .WithMany("Mercados")
                        .HasForeignKey("EventoId");
                });
#pragma warning restore 612, 618
        }
    }
}
